#######
# StatefulSet without any mounts.
# Data will be lost when nodes are down.
# It is not intended for scaling (default SeedProvider doesn't seem to resolve
# FQDN, so there is no way to specify seed node correctly).
#
# NOTE: There is gcr.io/google-samples/cassandra:v13 which seems to handle
# FQDN seeds it, but I choose to use official Cassandra image.
#
# NOTE: Performance optimizations has not been made.
#######
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:3.11.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            exec:
              command: ["/bin/bash", "-c", "exec", "/opt/ready-probe.sh"]
            initialDelaySeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: cassandra-ready-probe
              mountPath: /opt/ready-probe.sh
              subPath: ready-probe.sh
      volumes:
        - name: cassandra-ready-probe
          configMap:
            name: cassandra-ready-probe
---

#######
# Simple startup checker
#######
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-ready-probe
data:
  ready-probe.sh: |
    #!/bin/bash

    if [[ $(nodetool status | grep $POD_IP) == *"UN"* ]]; then
      exit 0;
    else
      exit 1;
    fi
---

#######
# Headless Service for Cassandra node discovery
#######
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: cassandra
