{
 "title": "Tweetserver",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "create_tweet Request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tweetserver_http_requests_total{handler=\"create_tweet\"}[1m]))",
     "legendFormat": "overall"
    }
   ]
  },
  {
   "title": "tweets_by_tag Request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tweetserver_http_requests_total{handler=\"tweets_by_tag\"}[1m]))"
    }
   ]
  },
  {
   "title": "create_tweet 95%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tweetserver_http_response_time_hist_bucket{handler=\"create_tweet\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "tweets_by_tag 95%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tweetserver_http_response_time_hist_bucket{handler=\"tweets_by_tag\"}[5m])) by (le))"
    }
   ]
  }
 ]
}